Docs migration
nuxt-community/analytics-module pull request #90
Opened 2020-10-14 21:31 UTC by mayashavin

2020-10-15 15:55 UTC, ricardogobbosouza requested changes
Nice work @mayashavin, really amazing 😄 

If you can also update **README.md** as https://github.com/nuxt-community/mdx-module it would be incredible

2020-10-15 15:55 UTC, ricardogobbosouza commented on docs/content/en/options.md
> +
Can add asyncID option?
https://github.com/nuxt-community/analytics-module/issues/85

Allow an asynchronous function to load the id
https://github.com/nuxt-community/analytics-module/blob/master/lib/plugin.js#L9

2020-10-16 05:45 UTC, mayashavin commented
@ricardogobbosouza done :)

2020-10-16 10:03 UTC, ricardogobbosouza approved these changes

2020-10-16 10:42 UTC, merged